allure-framework/allure-ruby

.github/workflows/build.yml
rake/test.rb

github.event.after doesn't exist on first creation of pull request so commiter info is incorrect.

Fix commiter info of coveralls for initial pull_request creation

---

allure-rspec/lib/allure_rspec/formatter.rb
allure-rspec/lib/allure_rspec/rspec_model.rb
allure-rspec/spec/integration/full_report_spec.rb

Fix issues when using context and describe blocks without description.
Fix issue with creating parent and sub suite labels without value.
Closes #127

Use default values for anonymous groups instead of empty strings

---

allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb

Fixed the logger for adding the stopping test step name.

stop_test_step name fix in logger

---

Gemfile
Gemfile.lock
allure-cucumber/lib/allure_cucumber/formatter.rb
allure-cucumber/lib/allure_cucumber/models/cucumber_model.rb
allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
allure-rspec/lib/allure_rspec/formatter.rb
allure-ruby-commons/lib/allure_ruby_commons/config.rb
allure-ruby-commons/spec/fixtures/test_plan/correct/testplan.json
allure-ruby-commons/spec/fixtures/test_plan/malformed/testplan.json
allure-ruby-commons/spec/spec_helper.rb
allure-ruby-commons/spec/unit/config_spec.rb

Adds support for testplan.json for allure-rspec
* Uses id field as `allure_id` tag in rspec tests by passing tags to [filter_run_when_matching](https://rubydoc.info/github/rspec/rspec-core/RSpec/Core/Configuration#filter_run_when_matching-instance_method) method
* Filters out specs by full name
Note that if allure id is used, it will filter out all tests that do not match it, which basically means also every test that isn't marked with `allure_id` tag (will pass tests to filter by name if none specs match)
Adds support for testplan.json for allure-cucumber
* Uses test name to apply as regex for scenario name
Not implemented filter by tags as it doesn't look like it's possible to implement tag expression similar to rspec as cucumber doesn't run anything if not scenarios match.
Closes #159

Add support for testplan.json

---

allure-rspec/lib/allure_rspec/tag_parser.rb
allure-rspec/spec/unit/formatter_example_started_spec.rb

The goal of this PR is to automatically report Rspec tags and support backward compatibility with existing labels `allure_`.

feat: add support for rspec tags

---

allure-cucumber/lib/allure_cucumber/formatter.rb

Avoid execution error while using Afterstep hooks. The current implementation of the formatter does not include Afterstep hook behaviour, causing unexpected crashes while cucumber executes this step.
As per cucumber docs (https://cucumber.io/docs/cucumber/api/#hooks): 
`AfterStep
AfterStep do |scenario|
end
` 
This pull request is a workaround, it would be great to implement a solution that handles the Afterstep hook properly.

Avoid test execution failure while using Afterstep hooks 

---

allure-cucumber/lib/allure_cucumber/config.rb
allure-cucumber/lib/allure_cucumber/formatter.rb
allure-cucumber/spec/spec_helper.rb
allure-rspec/lib/allure_rspec/config.rb
allure-rspec/lib/allure_rspec/formatter.rb
allure-rspec/spec/spec_helper.rb
allure-ruby-commons/spec/spec_helper.rb
allure-ruby-commons/spec/unit/allure_spec.rb
allure-ruby-commons/spec/unit/attachment_spec.rb
allure-ruby-commons/spec/unit/test_fixture_spec.rb
allure-ruby-commons/spec/unit/test_result_container_spec.rb
allure-ruby-commons/spec/unit/test_result_spec.rb
allure-ruby-commons/spec/unit/test_step_spec.rb

* Remove second copy of lifecycle and custom lifecycle injection in to rspec example instance
* Refactor allure-ruby-commons tests
---
📝 [Latest allure report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/267/merge/843109234/index.html)

Remove lifecycle copy in thread variable for rspec reporter

---

allure-cucumber/lib/allure-cucumber.rb
allure-cucumber/lib/allure_cucumber/config.rb
allure-cucumber/lib/allure_cucumber/formatter.rb
allure-cucumber/lib/allure_cucumber/models/cucumber_model.rb
allure-cucumber/spec/spec_helper.rb
allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
allure-rspec/lib/allure-rspec.rb
allure-rspec/lib/allure_rspec/config.rb
allure-rspec/lib/allure_rspec/formatter.rb
allure-rspec/spec/spec_helper.rb
allure-rspec/spec/unit/formatter_example_started_spec.rb
allure-ruby-commons/README.md
allure-ruby-commons/lib/allure_ruby_commons/config.rb
allure-ruby-commons/lib/allure_ruby_commons/model/executable_item.rb
allure-ruby-commons/lib/allure_ruby_commons/model/test_result.rb
allure-ruby-commons/spec/unit/test_result_spec.rb

Add support for custom allure environments:
Environment is provided via:
* `ALLURE_ENVIRONMENT` environment variable
* `Config.environment` accessor
Allure environment value will be prefixed to test names if present in order to separate same tests running in different environments
---
📝 [Latest allure report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/268/merge/845510770/index.html)

Different test environments support

---

allure-cucumber/lib/allure_cucumber/formatter.rb
allure-cucumber/spec/spec_helper.rb
allure-rspec/lib/allure_rspec/formatter.rb
allure-rspec/spec/spec_helper.rb

---
📝 [Latest allure report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/271/merge/849506767/index.html)

Consistent lifecycle and config access by formatters

---

allure-cucumber/lib/allure_cucumber/config.rb
allure-rspec/README.md
allure-rspec/lib/allure_rspec/config.rb
allure-rspec/lib/allure_rspec/metadata_parser.rb

* Adds ability to change values for `epic`, `feature`, `story`, `severity`, `issue` and `tms tags`
---
📝 [Latest allure report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/272/merge/850359085/index.html)

RSpec: Ability to configure special allure tags

---

allure-cucumber/lib/allure_cucumber/models/metadata_parser.rb
allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
allure-rspec/lib/allure_rspec/metadata_parser.rb
allure-rspec/spec/unit/formatter_example_started_spec.rb
allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb
allure-ruby-commons/spec/unit/result_utils_spec.rb

In case full url is used for issue and tms links, don't use full url as name in report

Use prefix/tag for link names if full url used

---

allure-ruby-commons/lib/allure_ruby_commons/file_writer.rb
allure-ruby-commons/lib/allure_ruby_commons/model/01_jsonable.rb

Related to: https://github.com/allure-framework/allure-ruby/issues/335
By not relying on global options, this should make sure if project already uses Oj, it's not impacted by whatever options the project might be setting.

Remove global default Oj options

---

allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb

The `config.results_directory` string is being passed into the `FileWriter`
initializer. The `results_directory` can be changed via the `Allure.configure`
block. Since ruby passes strings by value, this necessitates that the
`Allure.configure` block be called prior to initializing the
`AllureLifecycle` object.
Moving the `FileWriter` to an instance method and memoizing such that it
will be initialized right before it is used for the first time. Thus
allowing for a less strict ordering.

Making file_writer lazily initialized

---

.github/workflows/test.yml
allure-rspec/spec/unit/formatter_start_spec.rb
allure-rspec/spec/unit/formatter_stop_spec.rb

Update allure report publisher version and post result in pr description
---
**rspec-3.0**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/366/merge/2172678259/index.html) for [7003b180](https://github.com/allure-framework/allure-ruby/pull/366/commits/7003b1808196962171057eb594d7ddba9e3fbb1b)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0 …
```

Update allure report publishing

---

.github/workflows/test.yml

**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/371/merge/2213303838/index.html) for [89fad658](https://github.com/allure-framework/allure-ruby/pull/371/commits/89fad6581dc83b230bf6da0d10de893257e91416)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0     | ✅     |
| allure-rspec        | 63     | 0      | 0       | 0     | ✅     |
| …
```

Bump publisher version

---

.github/dependabot.yml

**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/377/merge/2213364189/index.html) for [878f3cd4](https://github.com/allure-framework/allure-ruby/pull/377/commits/878f3cd411b17661f1cbf0f93463f68a042f5b46)
```markdown
| allure-ruby-commons | 270    | 0      | 0       | 0     | ✅     |
| allure-cucumber     | 96     | 0      | 0       | 0     | ✅     |
| …
```

Allow indirect dependency updates in lockfile

---

.github/workflows/test.yml

**report**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/393/merge/2449799590/index.html) for [4cfc8b40](https://github.com/allure-framework/allure-ruby/pull/393/commits/4cfc8b40da310b0f40aabedf7662c869d6b171d5)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0     | 96    | ✅     |
| allure-rspec …
```

Use container environment for allure-report publish

---

.github/workflows/test.yml

**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/424/merge/3085491998/index.html) for [9649f2a1](https://github.com/allure-framework/allure-ruby/pull/424/commits/9649f2a14920a605fcc11b91fa362ad98e57f583)
```markdown
| allure-ruby-commons | 270    | 0      | 0       | 0     | 270   | ✅     |
| allure-cucumber …
```

Publish report only when maintainer triggers ci run

---

.github/workflows/changelog.yml
.github/workflows/release.yml
Gemfile
Gemfile.lock
lib/tasks/version.rake

**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/433/merge/3256037702/index.html) for [2a2c861c](https://github.com/allure-framework/allure-ruby/pull/433/commits/2a2c861c76fdf25ea201305e5cd215a1e9901e18)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0     | 96    | ✅     |
| allure-rspec …
```

Add manual release workflow

---

.github/dependabot.yml
.github/release.yml
README.md

**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/434/merge/3256074080/index.html) for [9d8e999b](https://github.com/allure-framework/allure-ruby/pull/434/commits/9d8e999b15ba6037fdd461b8a99cb52123074bf8)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0     | 96    | ✅     |
| allure-rspec …
```

Use common github labels

---

allure-rspec/lib/allure_rspec/formatter.rb

RSpec trace can often contain ansi color escape codes. Clear these to make error messages more readable.
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/445/merge/3495112939/index.html) for [069e7674](https://github.com/allure-framework/allure-ruby/pull/445/commits/069e767426d4935075aba75155343e0fb733c42d)
```markdown
+---------------------+--------+--------+---------+-------+-------+ …
```

Clear ansi color escapes from rspec traces

---

Gemfile.lock
allure-ruby-commons/allure-ruby-commons.gemspec
allure-ruby-commons/lib/allure-ruby-commons.rb

Fixes: https://github.com/allure-framework/allure-ruby/issues/444
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/447/merge/3569229939/index.html) for [2d749819](https://github.com/allure-framework/allure-ruby/pull/447/commits/2d7498194e15e9de02817b21bc8f4198f3a50100)
```markdown
| allure-cucumber     | 96 …
```

Set correct status for expect failures in steps

---

.codeclimate.yml
allure-ruby-commons/lib/allure_ruby_commons/_json_helper.rb
allure-ruby-commons/lib/allure_ruby_commons/testplan.rb
allure-ruby-commons/spec/unit/testplan_spec.rb

**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/495/merge/5118631383/index.html) for [dc343cf5](https://github.com/allure-framework/allure-ruby/pull/495/commits/dc343cf5f6f8dfda601ed71d7e706b15e3d9752d)
```markdown
| allure-cucumber     | 192    | 0      | 0       | 0     | 192   | ✅     |
| allure-rspec …
```

Correctly handle failure to load testplan.json

---

.github/workflows/test.yml
allure-cucumber/spec/spec_helper.rb
allure-rspec/spec/spec_helper.rb
allure-ruby-commons/lib/allure_ruby_commons/model/01_jsonable.rb
allure-ruby-commons/lib/allure_ruby_commons/model/category.rb
allure-ruby-commons/lib/allure_ruby_commons/model/test_result.rb
allure-ruby-commons/lib/allure_ruby_commons/model/test_result_container.rb
allure-ruby-commons/spec/spec_helper.rb

Take in to account all test case parameters when generating history id to make sure it's unique based on parameters set for test case.
Fixes: https://github.com/allure-framework/allure-ruby/issues/494
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/498/merge/5192221103/index.html) for [c3d8c712](https://github.com/allure-framework/allure-ruby/pull/498/commits/c3d8c7122509004551f02e561fe1deaec9dc00c4)
```markdown
|                     | passed | failed | …
```

Calculate history id based on all test case parameters

---

.rubocop.yml
allure-cucumber/allure-cucumber.gemspec
allure-rspec/allure-rspec.gemspec
allure-ruby-commons/allure-ruby-commons.gemspec

**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/499/merge/5208875839/index.html) for [e15efa4f](https://github.com/allure-framework/allure-ruby/pull/499/commits/e15efa4facdc8cfed8cd66c9407020120f07f09e)
```markdown
| allure-cucumber     | 192    | 0      | 0       | 0     | 192   | ✅     |
| allure-rspec …
```

Drop ruby 2.7 support

---

allure-cucumber/README.md
allure-cucumber/lib/allure_cucumber/formatter.rb
allure-cucumber/spec/unit/formatter_test_step_stopped_spec.rb
allure-rspec/README.md
allure-ruby-commons/lib/allure-ruby-commons.rb
allure-ruby-commons/lib/allure_ruby_commons/config.rb
allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb

* Add ability to provide custom exception class that marks test as failed
* Use consistent status for step and test in cucumber
Closes https://github.com/allure-framework/allure-ruby/issues/529
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/531/merge/7940492520/index.html) for [63feb4aa](https://github.com/allure-framework/allure-ruby/pull/531/commits/63feb4aa277ec443e36114b50d2c8ae6fec2da52)
```markdown …
```

Add option to configure exception class for marking test as failed

---

allure-cucumber/lib/allure_cucumber/config.rb
allure-cucumber/spec/unit/allure_cucumber_spec.rb
allure-rspec/lib/allure_rspec/config.rb
allure-rspec/spec/unit/allure_rspec_spec.rb

Closes https://github.com/allure-framework/allure-ruby/issues/533
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/534/merge/8050111673/index.html) for [8e1f7a73](https://github.com/allure-framework/allure-ruby/pull/534/commits/8e1f7a73420095ee0a759beac8c0d4018568c9e2)
```markdown …
```

Correctly handle all common configuration options

---

allure-rspec/lib/allure_rspec/formatter.rb
allure-rspec/lib/allure_rspec/metadata_parser.rb
allure-rspec/spec/unit/formatter_example_started_spec.rb

Set location to where spec is located rather than location of where shared_example is defined.
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/539/merge/8330896158/index.html) for [751bc356](https://github.com/allure-framework/allure-ruby/pull/539/commits/751bc356eeece50d8c5cacf468c70009b20feec3)
```markdown …
```

Correctly detect location when shared example is used

---

allure-rspec/spec/unit/formatter_example_finished_spec.rb
allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb
allure-ruby-commons/spec/unit/result_utils_spec.rb

Resolving Issue: https://github.com/allure-framework/allure-ruby/issues/544

Fixing category page 404 error due to exception message being passed as nil

---

allure-ruby-commons/lib/allure_ruby_commons/step_annotation.rb
allure-ruby-commons/spec/unit/step_annotation_spec.rb

Fixes: https://github.com/allure-framework/allure-ruby/issues/549
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/550/merge/8973356773/index.html) for [996dbacb](https://github.com/allure-framework/allure-ruby/pull/550/commits/996dbacb8b01292ead9c0b427da3df33d24d444a)
```markdown …
```

Fix keyword arguments not being passed when using step annotation

---

.github/dependabot.yml
allure-ruby-commons/allure-ruby-commons.gemspec
allure-ruby-commons/lib/allure-ruby-commons.rb
allure-ruby-commons/lib/allure_ruby_commons/model/test_result.rb
allure-ruby-commons/lib/allure_ruby_commons/model/test_result_container.rb
allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb
allure-ruby-commons/spec/unit/file_writer_spec.rb

The `uuid` gem is archived on GitHub since Jan 1, 2024: https://github.com/assaf/uuid
Although one might consider it feature complete and no longer require any updates (in fact, the last update was made 5 years ago), I would still consider it a risk. Its transitive dependencies `macaddr` and `systemu` were updated in 2019 and 2015 respectively.
The change removes 3 dependencies: `uuid` » `macaddr` » `systemu`.
Ruby already has a way to generate UUIDs via `SecureRandom`. It is v4 (compared to v1 implemented by the `uuid` gem), but for Allure purposes it should make no difference. Another option is PRNG version implemented in `Random#uuid_v4` and `Random#uuid_v7`, but it requires an instance of PRNG, and so more code changes.

Remove uuid dependency

---

allure-cucumber/lib/allure_cucumber/models/cucumber_model.rb
allure-cucumber/spec/cucumber_helper.rb
allure-cucumber/spec/unit/formatter_test_case_stopped_spec.rb

Hello ! :) 
Cucumber allows to skip scenario using **skip_this_scenario** method : https://www.rubydoc.info/gems/cucumber/Cucumber/Glue/ProtoWorld#skip_this_scenario-instance_method
This method also accepts optional string argument to specify more info about why this particular scenario is skipped.
Currently Allure report does not show this reason, but it would be great if it could. (particularly great if test scenario skipping logic becomes complex over time)
I hacked around a bit and managed to make it work using monkeypatch. I would like to include these changes also to upstream.
TODO:
* handle failure details for skipped scenario same way as for failed
* add test for skipped scenario

Show skipped test reason in report

---

allure-ruby-commons/lib/allure-ruby-commons.rb
allure-ruby-commons/lib/allure_ruby_commons/model/parameter.rb
allure-ruby-commons/lib/allure_ruby_commons/model/test_result.rb
allure-ruby-commons/spec/unit/allure_spec.rb
allure-ruby-commons/spec/unit/test_result_spec.rb

Adding `excluded` and `mode` options for `Parameter` class for Ruby binding

Add excluded and mode attributes to Parameter
