allure-framework/allure-ruby

- allure-cucumber/lib/allure_cucumber/cucumber_model.rb
- allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
- allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb
- allure-ruby-commons/spec/unit/test_result_spec.rb
Adds language and framework labels to test case.
Closes #4
> Add framework and language labels to test case

- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
- allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb
- allure-ruby-commons/spec/unit/allure_spec.rb
- allure-ruby-commons/spec/unit/result_utils_spec.rb
- allure-ruby-commons/spec/unit/test_step_spec.rb
Add support for nested steps in allure lifecycle.
Closes #2
> Add nested steps support and custom step methods

- allure-cucumber/README.md
- allure-cucumber/lib/allure_cucumber/formatter.rb
- allure-cucumber/spec/integration/full_report_spec.rb
- allure-cucumber/spec/spec_helper.rb
- allure-ruby-commons/README.md
- allure-ruby-commons/lib/allure_ruby_commons/config.rb
* Adds option to clean allure-results dir from previous reporter version
> Add option to clean allure results dir

- Jenkinsfile
- tasks/release.rb
* Adds rake task for automated relase bump from pipeline
> Release task

- README.md
- allure-cucumber/allure-cucumber.gemspec
- allure-ruby-commons/allure-ruby-commons.gemspec
* Add correct metadata to gems
* Add downloads counter to readme
> Add metadata

- allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb
- allure-ruby-commons/spec/unit/result_utils_spec.rb
* Unit tests to make sure #34 is working
Closes #34
> Additional test for rspec aggregated error

- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
- allure-ruby-commons/lib/allure_ruby_commons/file_writer.rb
- allure-ruby-commons/spec/integration/full_report_spec.rb
- allure-ruby-commons/spec/unit/allure_spec.rb
- allure-ruby-commons/spec/unit/file_writer_spec.rb
- allure-ruby-commons/spec/unit/test_fixture_spec.rb
* Adds utility to enhance report with environment info
Closes #35
> Utility method to add environment info to report

- .github/release-drafter.yml
Add label as the one suggested by github
> Fix label name for improvements

- .codeclimate.yml
- .github/CONTRIBUTING.md
- .github/workflows/test.yml
- .gitignore
- .rubocop.yml
- .simplecov
- Gemfile.lock
- README.md
- allure.gemspec
- rake/test.rb
* Replace coveralls with codeclimate
> Code climate

- .codeclimate.yml
- allure-cucumber/lib/allure_cucumber/tag_parser.rb
- allure-rspec/lib/allure_rspec/rspec_model.rb
- allure-rspec/lib/allure_rspec/tag_parser.rb
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
* Fix some of the code issues reported by code climate
> Improve code quality

- .codeclimate.yml
- lib/task_helpers/cc_uploader.rb
* Update code climate reporter version
> Bump cc reporter version

- .github/workflows/release.yml
- script/add-rubygems-token.sh
* Don't create credentials file, read key from environment variable
> CI: Use api key from environment variable

- README.md
- allure-cucumber/README.md
- allure-cucumber/lib/allure-cucumber.rb
- allure-cucumber/lib/allure_cucumber/config.rb
- allure-cucumber/lib/allure_cucumber/models/tag_parser.rb
- allure-cucumber/spec/cucumber_helper.rb
- allure-cucumber/spec/integration/full_report_spec.rb
- allure-cucumber/spec/unit/allure_cucumber_spec.rb
- allure-rspec/README.md
- allure-rspec/lib/allure-rspec.rb
- allure-rspec/lib/allure_rspec/config.rb
- allure-rspec/lib/allure_rspec/tag_parser.rb
- allure-rspec/spec/integration/full_report_spec.rb
- allure-rspec/spec/spec_helper.rb
- allure-rspec/spec/unit/allure_rspec_spec.rb
- allure-ruby-commons/README.md
- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
- allure-ruby-commons/lib/allure_ruby_commons/config.rb
- allure-ruby-commons/lib/allure_ruby_commons/file_writer.rb
- allure-ruby-commons/spec/integration/full_report_spec.rb
- allure-ruby-commons/spec/spec_helper.rb
- allure-ruby-commons/spec/unit/file_writer_spec.rb
- allure-ruby-commons/spec/unit/lifecycle_spec.rb
* Inherits the common configuration in adapter specific config, so base allure config doesn't have to be called explicitly
> Inherit common configuration in adapter specific config

- Gemfile.lock
- allure-cucumber/allure-cucumber.gemspec
* Update to final cucumber 4 release
> Update to cucumber 4

- allure-ruby-commons/README.md
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
- allure-ruby-commons/lib/allure_ruby_commons/config.rb
- allure-ruby-commons/spec/spec_helper.rb
- allure-ruby-commons/spec/unit/attachment_spec.rb
- allure-ruby-commons/spec/unit/test_fixture_spec.rb
- allure-ruby-commons/spec/unit/test_result_container_spec.rb
- allure-ruby-commons/spec/unit/test_result_spec.rb
- allure-ruby-commons/spec/unit/test_step_spec.rb
> Add debug logging to allure lifecycle

- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
> Remove everything from allure-results folder

- allure-ruby-commons/lib/allure_ruby_commons/file_writer.rb
- allure-ruby-commons/lib/allure_ruby_commons/model/jsonable.rb
> Remove max nesting limit when creating results

- Gemfile.lock
- allure-cucumber/allure-cucumber.gemspec
- allure-rspec/allure-rspec.gemspec
- allure-ruby-commons/allure-ruby-commons.gemspec
- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/lib/allure_ruby_commons/file_writer.rb
- allure-ruby-commons/lib/allure_ruby_commons/model/jsonable.rb
* Replace JSON with Oj
* Simplify jsonable by simply using oj with to_hash method
> Replace JSON with Oj

- lib/task_helpers/cc_uploader.rb
- lib/task_helpers/simplecov_merger.rb
- lib/tasks/test.rake
* Update cc reporter and remove manual json updates
> Update codeclimate test reporter to v0.9.0

- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/spec/unit/allure_spec.rb
> Return the result of passed block in run_step method

- .github/workflows/draft-release.yml
- .github/workflows/release.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
Remove the ubuntu-latest warnings
> Use specific ubuntu version in workflows

- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/spec/unit/allure_spec.rb
I’ve added an helper method to add a tag  to the current test case.
> Add tag support

- allure-cucumber/lib/allure_cucumber/formatter.rb
- allure-cucumber/lib/allure_cucumber/models/cucumber_model.rb
- allure-cucumber/spec/cucumber_helper.rb
- allure-cucumber/spec/integration/full_report_spec.rb
- allure-cucumber/spec/unit/formatter_test_step_started_spec.rb
- allure-cucumber/spec/unit/formatter_test_step_stopped_spec.rb
Adds proper support for AfterStep hook.
Closes: #210
> Add support for after_step hook

- allure-cucumber/lib/allure_cucumber/models/metadata_parser.rb
- allure-cucumber/spec/integration/full_report_spec.rb
- allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
- allure-rspec/lib/allure_rspec/metadata_parser.rb
- allure-rspec/spec/integration/full_report_spec.rb
- allure-rspec/spec/unit/formatter_example_started_spec.rb
* do not set story label by default as it creates unnecessary nested layer in behaviours tab
> do not set story label by default

- allure-cucumber/spec/spec_helper.rb
- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/spec/spec_helper.rb
---
📝 [Latest allure report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/263/merge/828968360/index.html)
> Replace epic, feature, story and suite labels instead of creating copy on manual calls

- README.md
---
📝 [Latest allure report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/265/merge/829144441/index.html)
> Add allure report badge

- allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
- allure-rspec/spec/unit/formatter_example_started_spec.rb
---
📝 [Latest allure report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/269/merge/845537582/index.html)
> Remove leftover test tags

- allure-cucumber/lib/allure_cucumber/formatter.rb
- allure-cucumber/spec/spec_helper.rb
> Correctly set results directory in allure-cucumber

- allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
- allure-rspec/lib/allure_rspec/formatter.rb
- allure-rspec/spec/unit/formatter_example_started_spec.rb
- allure-ruby-commons/lib/allure_ruby_commons/model/executable_item.rb
- allure-ruby-commons/lib/allure_ruby_commons/model/test_result.rb
- allure-ruby-commons/spec/unit/test_result_spec.rb
Fixes setting custom allure environment name
> Fix custom allure environment setting

- allure-cucumber/README.md
- allure-cucumber/lib/allure_cucumber/config.rb
- allure-cucumber/lib/allure_cucumber/formatter.rb
- allure-cucumber/spec/unit/formatter_test_run_started_spec.rb
- allure-rspec/README.md
- allure-rspec/lib/allure_rspec/config.rb
- allure-rspec/lib/allure_rspec/formatter.rb
- allure-rspec/spec/spec_helper.rb
- allure-rspec/spec/unit/formatter_start_spec.rb
- allure-ruby-commons/README.md
- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
- allure-ruby-commons/lib/allure_ruby_commons/config.rb
- allure-ruby-commons/spec/unit/lifecycle_spec.rb
Adds ability to add environment and categories via allure config object
> Add ability to set environment.properties and categories.json via allure configuration

- allure-cucumber/lib/allure_cucumber/formatter.rb
- allure-cucumber/spec/unit/formatter_test_run_finished_spec.rb
- allure-rspec/lib/allure_rspec/formatter.rb
- allure-rspec/spec/unit/formatter_stop_spec.rb
- allure-ruby-commons/README.md
- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
- allure-ruby-commons/spec/unit/lifecycle_spec.rb
Ability to configure environment.properties as a callback executed after test run is finished
> allow configuring environment.properties via proc

- .github/CONTRIBUTING.md
- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/lib/allure_ruby_commons/model/executable_item.rb
- allure-ruby-commons/lib/allure_ruby_commons/model/test_result.rb
- allure-ruby-commons/spec/unit/allure_spec.rb
- allure-ruby-commons/spec/unit/test_step_spec.rb
resolves #346 
- Added new tests for steps with parameters
- Ensured the coverage is not decreased
> Add support for parameters in step

- allure-ruby-commons/lib/allure-ruby-commons.rb
- allure-ruby-commons/spec/unit/allure_spec.rb
Add `set_flaky`, `set_muted`, `set_known` helpers
> Add status details modifier helpers

- .github/dependabot.yml
- .github/workflows/test.yml
- .solargraph.yml
---
**rspec-3.0**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/368/merge/2173439569/index.html) for [bba9affd](https://github.com/allure-framework/allure-ruby/pull/368/commits/bba9affdba62b4cb44dcd33cf638098e775dcb0e)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0     | ✅     |
| allure-rspec        | 63     | 0      | 0       | 0     | ✅ …
```
> Update dependabot configuration

- README.md
- allure-cucumber/README.md
- allure-rspec/README.md
- allure-ruby-commons/README.md
---
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/370/merge/2213280780/index.html) for [30b626fd](https://github.com/allure-framework/allure-ruby/pull/370/commits/30b626fdc2269b4837d5a8e446939f3ee60f0341)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0     | ✅     |
| allure-rspec        | 63     | 0      | 0       | 0     | ✅ …
```
> Improve main README.md

- lib/tasks/version.rake
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/401/merge/2599565964/index.html) for [59371a4b](https://github.com/allure-framework/allure-ruby/pull/401/commits/59371a4b848636b74e2f4c4eea9b7f4c778592aa)
```markdown
| allure-ruby-commons | 270    | 0      | 0       | 0     | 270   | ✅     |
| allure-cucumber …
```
> Fix test job on ci

- .github/workflows/release.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/416/merge/2851553555/index.html) for [1af12067](https://github.com/allure-framework/allure-ruby/pull/416/commits/1af12067608eb14bee116de53d87098252bca8b0)
```markdown
| allure-cucumber     | 96     | 0      | 0       | 0     | 96    | ✅     |
| allure-rspec …
```
> Automatically publish release

- allure-ruby-commons/lib/allure_ruby_commons/_json_helper.rb
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/493/merge/5109513778/index.html) for [926ba016](https://github.com/allure-framework/allure-ruby/pull/493/commits/926ba016ccb1ee375c2fcd272b24c8e0355b5b8b)
```markdown
| allure-cucumber     | 192    | 0      | 0       | 0     | 192   | ✅     |
| allure-rspec …
```
> Fix missing require json

- .github/workflows/release.yml
- .github/workflows/test.yml
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/496/merge/5141683875/index.html) for [f714d98f](https://github.com/allure-framework/allure-ruby/pull/496/commits/f714d98f9c8abb08c23036080d01793776704156)
```markdown
| allure-cucumber     | 192    | 0      | 0       | 0     | 192   | ✅     |
| allure-rspec …
```
> Run allure report in pull requests

- allure-cucumber/allure-cucumber.gemspec
**rspec**: ✅ [test report](https://storage.googleapis.com/allure-test-reports/allure-ruby/refs/pull/540/merge/8331011218/index.html) for [1cea179c](https://github.com/allure-framework/allure-ruby/pull/540/commits/1cea179c092fec40c8895451a52f21a2203e1c3b)
```markdown
| allure-cucumber     | 272    | 0      | 0 …
```
> Do not use CSV from standard library
